import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

export type Language = 'en' | 'mr' | 'hi';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.courses': 'Courses',
    'nav.labs': 'Labs',
    'nav.certifications': 'Certifications',
    'nav.internships': 'Opportunities',
    'nav.ai_advisor': 'AI Advisor',
    'nav.progress': 'My Progress',
    'nav.login': 'Log In',
    'nav.register': 'Register',
    'nav.logout': 'Sign Out',
    'nav.notifications': 'Notifications',

    // Hero & Home
    'hero.title': 'Empowering Rural Education',
    'hero.subtitle': 'Access world-class learning resources, book labs, and find internships tailored for rural students.',
    'hero.cta': 'Get Started',
    'hero.welcome_back': 'Welcome back',
    'hero.dashboard_sub': 'Access your dedicated portal below to continue your technical journey.',
    'stats.students': 'Students Enrolled',
    'stats.labs': 'Partner Labs',
    'stats.courses': 'Courses Available',
    'stats.internships': 'Internships & Jobs',

    // Sidebar Menus
    'menu.Dashboard': 'Dashboard',
    'menu.Courses': 'Courses',
    'menu.Labs': 'Labs',
    'menu.My Learning': 'My Learning',
    'menu.Progress': 'Progress',
    'menu.Quizzes': 'Quizzes',
    'menu.Certificates': 'Certificates',
    'menu.Opportunities/Apply': 'Opportunities / Apply',
    'menu.AI Advisor': 'AI Advisor',
    'menu.Notifications': 'Notifications',
    'menu.Profile': 'Profile',
    'menu.My Courses': 'My Courses',
    'menu.Create/Edit Courses': 'Create / Edit Courses',
    'menu.Modules/Lectures': 'Modules & Lectures',
    'menu.Upload Videos/PDFs/Notes': 'Upload Resources',
    'menu.Enrollments': 'Student Enrollments',
    'menu.Student Progress': 'Student Progress',
    'menu.Create/Manage Jobs & Internships': 'Manage Job Postings',
    'menu.Applicants': 'Candidate Applicants',
    'menu.Student Profiles': 'Student Talent Profiles',
    'menu.Shortlist/Reject': 'Shortlist & Hiring',
    'menu.Application Status': 'Application Status',
    'menu.Company Profile': 'Company Profile',
    'menu.Manage Students': 'Manage Students',
    'menu.Trainers': 'Manage Trainers',
    'menu.Recruiters': 'Manage Recruiters',
    'menu.Opportunities': 'Manage Opportunities',
    'menu.Users/Roles': 'Users & Role Controls',
    'menu.Reports & Settings': 'Reports & Settings',
    'menu.portal': 'Portal',

    // Buttons & Common Actions
    'btn.enroll_now': 'Enroll Now',
    'btn.continue_learning': 'Continue Learning',
    'btn.view_syllabus': 'View Syllabus',
    'btn.start_course': 'Start Course',
    'btn.book_slot': 'Book Lab Slot',
    'btn.apply_now': 'Apply Now',
    'btn.submit_app': 'Submit Application',
    'btn.cancel': 'Cancel',
    'btn.close': 'Close',
    'btn.save': 'Save Changes',
    'btn.edit': 'Edit Profile',
    'btn.view_cert': 'View Certificate',
    'btn.print_cert': 'Print / Download Diploma',
    'btn.predict_gap': 'Predict Skill Gap & Roadmap',
    'btn.regenerate': 'Regenerate Roadmap',
    'btn.save_roadmap': 'Save Progress',
    'btn.download_roadmap': 'Download Roadmap',
    'btn.copy': 'Copy',
    'btn.shortlist': 'Shortlist',
    'btn.review': 'Review',
    'btn.reject': 'Reject',
    'btn.explore': 'Explore',

    // Categories & Filters
    'cat.all': 'All',
    'cat.hardware': 'Hardware',
    'cat.software': 'Software',
    'cat.technology': 'Technology',
    'cat.agriculture': 'Agriculture',
    'cat.business': 'Business',
    'cat.categories': 'Categories',
    'cat.level': 'Level',
    'cat.beginner': 'Beginner',
    'cat.intermediate': 'Intermediate',
    'cat.advanced': 'Advanced',
    'cat.search_courses': 'Search by title, skills, hardware, software...',
    'cat.search_labs': 'Search by lab name, location, equipment...',
    'cat.search_opps': 'Search jobs, companies, skills, locations...',

    // Courses Page
    'courses.title': 'Industry & Technical Courses',
    'courses.subtitle': 'Practical, localized, and job-ready technical courses with laboratory assignments.',
    'courses.syllabus_title': 'Course Curriculum & Syllabus',
    'courses.skills_gained': 'Skills You Will Gain',
    'courses.modules_included': 'Modules Included',
    'courses.duration': 'Duration',
    'courses.provider': 'Provider',

    // Labs Page
    'labs.title': 'Book Regional Labs & Workshops',
    'labs.subtitle': 'Access state-of-the-art hardware workbenches, testing centers, and computer terminals in Koprgaon.',
    'labs.available_slots': 'Available Slots',
    'labs.capacity': 'Capacity',
    'labs.facilities': 'Key Facilities',
    'labs.equipment': 'Equipment & Workstations',
    'labs.incharge': 'Lab In-Charge',
    'labs.timings': 'Timings',
    'labs.rules': 'Safety & Guidelines',
    'labs.booking_title': 'Book a Lab Workstation',
    'labs.select_date': 'Select Date',
    'labs.select_time': 'Select Time Slot',
    'labs.purpose': 'Purpose / Practical Objective',
    'labs.confirm_booking': 'Confirm & Reserve Slot',
    'labs.booked_success': 'Lab session booked successfully!',

    // Certifications Page
    'cert.title': 'Official Verifiable Certifications',
    'cert.subtitle': 'Demonstrate your practical technical competencies to recruiters with verified diplomas.',
    'cert.verified_badge': 'Authentic & Verified Credential',
    'cert.issued_to': 'This is proudly presented to',
    'cert.for_mastering': 'for successfully demonstrating mastery in',
    'cert.cert_id': 'Certificate ID',
    'cert.issued_date': 'Issue Date',
    'cert.grade': 'Competency Grade',
    'cert.authorized_by': 'Authorized Examiner',
    'cert.skills_verified': 'Demonstrated Technical Skills',
    'cert.no_certs': 'No completed course certificates yet. Complete a course and assessment quiz to unlock your certificate.',

    // Internships & Opportunities
    'internships.title': 'Opportunities & Placements',
    'internships.subtitle': 'Connect directly with regional employers, agricultural tech enterprises, and industrial workshops.',
    'internships.stipend': 'Compensation / Stipend',
    'internships.location': 'Location',
    'internships.type': 'Engagement Type',
    'internships.deadline': 'Apply Before',
    'internships.eligibility': 'Eligibility',
    'internships.applied_badge': 'Applied',

    // AI Advisor & Skill Gap Predictor
    'ai.title': 'AI Career & Skill Advisor',
    'ai.subtitle': 'Personalized skill gap prediction, course matching & customized career roadmaps',
    'ai.tab_predictor': 'Skill Gap Predictor & Roadmap',
    'ai.tab_chat': 'AI Career Chat',
    'ai.step1_title': '1. Select Target Career Role',
    'ai.step2_title': '2. Your Current Skills',
    'ai.edu_level': 'Education Level',
    'ai.pace': 'Weekly Pace',
    'ai.readiness_title': 'Target Role Readiness',
    'ai.acquired_skills': 'Acquired Skills',
    'ai.skill_gaps': 'Identified Skill Gaps',
    'ai.rec_course': 'Recommended Course',
    'ai.rec_lab': 'Hands-On Practical Lab',
    'ai.roadmap_title': 'Step-by-Step Personalized Learning & Lab Roadmap',

    // Lecture & Learn
    'lecture.lang_select': 'Lecture Language',
    'lecture.download_pdf': 'Download Module Notes (PDF)',
    'lecture.download_guide': 'Download Practical Lab Guide (PDF)',
    'lecture.download_cheatsheet': 'Download Quick Cheatsheet',
    'lecture.complete_next': 'Complete & Next Lesson',
    'lecture.take_quiz': 'Complete Lessons & Take Quiz',
    'lecture.quiz_title': 'Course Competency Assessment Quiz',
    'lecture.submit_quiz': 'Submit Quiz & Verify Skills',
    'lecture.cert_earned': 'Official Certificate Earned',
    'lecture.curriculum': 'Curriculum Modules',
    'lecture.technical_overview': 'Technical Overview & Practical Focus',
    'lecture.equipment_setup': 'Recommended Equipment & Lab Setup',
    'lecture.safety_tips': 'Safety Guidelines & Field Tips',

    // Progress & Profile
    'progress.title': 'Student Progress & Profile',
    'progress.subtitle': 'Track your course completions, lab bookings, and career readiness.',
    'progress.enrolled_courses': 'My Enrolled Courses',
    'progress.lab_bookings': 'My Lab Bookings',
    'progress.profile_details': 'Profile Details & Preferences',
    'progress.education': 'Education',
    'progress.skills': 'Skills',
    'progress.interests': 'Interests',
    'progress.career_goal': 'Career Goal',
    'progress.trainer_panel': 'Trainer: Student Enrollments & Progress',
    'progress.recruiter_panel': 'Recruiter: Candidate Applications & Shortlisting',
    'progress.admin_panel': 'Admin Console: System Overview & Role Management',

    // Auth & Form
    'auth.login_title': 'Welcome Back to RuralLearn',
    'auth.register_title': 'Create Your RuralLearn Account',
    'auth.email': 'Email Address',
    'auth.password': 'Password',
    'auth.name': 'Full Name',
    'auth.role': 'Select Role',
    'auth.no_account': "Don't have an account?",
    'auth.have_account': 'Already have an account?',
    'footer.text': '© 2024 RuralLearn. Empowering rural youth with technical skills.'
  },
  mr: {
    // Navigation
    'nav.home': 'मुख्यपृष्ठ',
    'nav.courses': 'अभ्यासक्रम',
    'nav.labs': 'लॅब्स',
    'nav.certifications': 'प्रमाणपत्रे',
    'nav.internships': 'संधी व नोकऱ्या',
    'nav.ai_advisor': 'एआय सल्लागार',
    'nav.progress': 'माझी प्रगती',
    'nav.login': 'लॉगिन',
    'nav.register': 'नोंदणी',
    'nav.logout': 'बाहेर पडा',
    'nav.notifications': 'सूचना',

    // Hero & Home
    'hero.title': 'ग्रामीण शिक्षणाचे सक्षमीकरण',
    'hero.subtitle': 'जागतिक दर्जाची तांत्रिक शिक्षण संसाधने मिळवा, लॅब बुक करा आणि ग्रामीण विद्यार्थ्यांसाठी इंटर्नशिप शोधा.',
    'hero.cta': 'सुरुवात करा',
    'hero.welcome_back': 'स्वागत आहे',
    'hero.dashboard_sub': 'तुमचा तांत्रिक प्रवास पुढे चालू ठेवण्यासाठी खालील पोर्टल उघडा.',
    'stats.students': 'नोंदणीकृत विद्यार्थी',
    'stats.labs': 'भागीदार लॅब्स',
    'stats.courses': 'उपलब्ध अभ्यासक्रम',
    'stats.internships': 'इंटर्नशिप व नोकऱ्या',

    // Sidebar Menus
    'menu.Dashboard': 'डॅशबोर्ड',
    'menu.Courses': 'अभ्यासक्रम',
    'menu.Labs': 'लॅब्स',
    'menu.My Learning': 'माझे शिक्षण',
    'menu.Progress': 'प्रगती',
    'menu.Quizzes': 'चाचण्या व क्विझ',
    'menu.Certificates': 'प्रमाणपत्रे',
    'menu.Opportunities/Apply': 'संधी व अर्ज',
    'menu.AI Advisor': 'एआय सल्लागार',
    'menu.Notifications': 'सूचना',
    'menu.Profile': 'प्रोफाइल',
    'menu.My Courses': 'माझे अभ्यासक्रम',
    'menu.Create/Edit Courses': 'अभ्यासक्रम तयार/संपादित करा',
    'menu.Modules/Lectures': 'धडे व व्याख्याने',
    'menu.Upload Videos/PDFs/Notes': 'संसाधने अपलोड करा',
    'menu.Enrollments': 'विद्यार्थी प्रवेश',
    'menu.Student Progress': 'विद्यार्थी प्रगती',
    'menu.Create/Manage Jobs & Internships': 'नोकऱ्या व्यवस्थापित करा',
    'menu.Applicants': 'अर्जदार विद्यार्थी',
    'menu.Student Profiles': 'विद्यार्थी कौशल्य प्रोफाइल',
    'menu.Shortlist/Reject': 'निवड व भरती',
    'menu.Application Status': 'अर्जाची स्थिती',
    'menu.Company Profile': 'कंपनी प्रोफाइल',
    'menu.Manage Students': 'विद्यार्थी व्यवस्थापन',
    'menu.Trainers': 'प्रशिक्षक व्यवस्थापन',
    'menu.Recruiters': 'कंपन्या व्यवस्थापन',
    'menu.Opportunities': 'संधी व्यवस्थापन',
    'menu.Users/Roles': 'वापरकर्ते व भूमिका',
    'menu.Reports & Settings': 'अहवाल व सेटिंग्ज',
    'menu.portal': 'पोर्टल',

    // Buttons & Actions
    'btn.enroll_now': 'आता प्रवेश घ्या',
    'btn.continue_learning': 'शिक्षण सुरू ठेवा',
    'btn.view_syllabus': 'अभ्यासक्रम पहा',
    'btn.start_course': 'अभ्यासक्रम सुरू करा',
    'btn.book_slot': 'लॅब स्लॉट बुक करा',
    'btn.apply_now': 'अर्ज करा',
    'btn.submit_app': 'अर्ज सादर करा',
    'btn.cancel': 'रद्द करा',
    'btn.close': 'बंद करा',
    'btn.save': 'बदल जतन करा',
    'btn.edit': 'प्रोफाइल संपादित करा',
    'btn.view_cert': 'प्रमाणपत्र पहा',
    'btn.print_cert': 'प्रमाणपत्र प्रिंट / डाउनलोड करा',
    'btn.predict_gap': 'कौशल्य अंतर व रोडमॅप तपासा',
    'btn.regenerate': 'रोडमॅप पुन्हा तयार करा',
    'btn.save_roadmap': 'प्रगती जतन करा',
    'btn.download_roadmap': 'रोडमॅप डाउनलोड करा',
    'btn.copy': 'कॉपी करा',
    'btn.shortlist': 'शॉर्टलिस्ट',
    'btn.review': 'तपासा',
    'btn.reject': 'नाकारा',
    'btn.explore': 'माहिती घ्या',

    // Categories & Filters
    'cat.all': 'सर्व',
    'cat.hardware': 'हार्डवेअर',
    'cat.software': 'सॉफ्टवेअर',
    'cat.technology': 'तंत्रज्ञान',
    'cat.agriculture': 'शेती व कृषी',
    'cat.business': 'व्यवसाय',
    'cat.categories': 'विभाग',
    'cat.level': 'पातळी',
    'cat.beginner': 'नवशिक्या (Beginner)',
    'cat.intermediate': 'मध्यम (Intermediate)',
    'cat.advanced': 'प्रगत (Advanced)',
    'cat.search_courses': 'शीर्षक, कौशल्य, हार्डवेअर किंवा सॉफ्टवेअरनुसार शोधा...',
    'cat.search_labs': 'लॅबचे नाव, पत्ता किंवा उपकरणांनुसार शोधा...',
    'cat.search_opps': 'नोकऱ्या, कंपन्या, कौशल्ये किंवा ठिकाण शोधा...',

    // Courses Page
    'courses.title': 'तांत्रिक व व्यावसायिक अभ्यासक्रम',
    'courses.subtitle': 'उद्योग-उपयुक्त, स्थानिक भाषेत आणि प्रात्यक्षिक लॅबसह तयार केलेले कौशल्य अभ्यासक्रम.',
    'courses.syllabus_title': 'अभ्यासक्रम तपशील व विषय',
    'courses.skills_gained': 'प्राप्त होणारी कौशल्ये',
    'courses.modules_included': 'समाविष्ट असलेले धडे',
    'courses.duration': 'कालावधी',
    'courses.provider': 'संस्था / प्रदाता',

    // Labs Page
    'labs.title': 'लॅब व कार्यशाळा बुक करा',
    'labs.subtitle': 'कोपरगाव परिसरातील अत्याधुनिक हार्डवेअर बेंच, टेस्टिंग सेंटर्स आणि संगणक लॅब वापरा.',
    'labs.available_slots': 'उपलब्ध स्लॉट',
    'labs.capacity': 'एकूण क्षमता',
    'labs.facilities': 'प्रमुख सुविधा',
    'labs.equipment': 'उपलब्ध उपकरणे व मशिन्स',
    'labs.incharge': 'लॅब प्रमुख / मार्गदर्शक',
    'labs.timings': 'वेळ',
    'labs.rules': 'सुरक्षा नियम व मार्गदर्शक तत्त्वे',
    'labs.booking_title': 'लॅब वर्कस्टेशन बुक करा',
    'labs.select_date': 'तारीख निवडा',
    'labs.select_time': 'वेळेचा स्लॉट निवडा',
    'labs.purpose': 'प्रात्यक्षिकाचा उद्देश / हेतू',
    'labs.confirm_booking': 'स्लॉट निश्चित करा',
    'labs.booked_success': 'लॅब सेशन यशस्वीपणे बुक झाले!',

    // Certifications Page
    'cert.title': 'अधिकृत पडताळणीयोग्य प्रमाणपत्रे',
    'cert.subtitle': 'उद्योगजगत आणि कंपन्यांसाठी पडताळणीयोग्य डिजिटल डिप्लोमासह तुमचे तांत्रिक कौशल्य सिद्ध करा.',
    'cert.verified_badge': 'प्रमाणित व पडताळणीयोग्य डिप्लोमा',
    'cert.issued_to': 'हे प्रमाणपत्र सन्मानपूर्वक प्रदान करण्यात येत आहे',
    'cert.for_mastering': 'या विषयातील प्रात्यक्षिक प्रभुत्व सिद्ध केल्याबद्दल:',
    'cert.cert_id': 'प्रमाणपत्र क्रमांक',
    'cert.issued_date': 'जारी केल्याची तारीख',
    'cert.grade': 'कौशल्य श्रेणी',
    'cert.authorized_by': 'अधिकृत परीक्षक',
    'cert.skills_verified': 'पडताळलेली तांत्रिक कौशल्ये',
    'cert.no_certs': 'अद्याप कोणतेही प्रमाणपत्र नाही. अभ्यासक्रम पूर्ण करा आणि प्रमाणपत्र मिळवण्यासाठी चाचणी द्या.',

    // Internships & Opportunities
    'internships.title': 'नोकरी व इंटर्नशिप संधी',
    'internships.subtitle': 'स्थानिक उद्योग, कृषी तंत्रज्ञान कंपन्या आणि औद्योगिक कार्यशाळांशी थेट जोडले जा.',
    'internships.stipend': 'विद्यावेतन / पगार',
    'internships.location': 'स्थान',
    'internships.type': 'कामाचा प्रकार',
    'internships.deadline': 'अंतिम मुदत',
    'internships.eligibility': 'पात्रता',
    'internships.applied_badge': 'अर्ज केला आहे',

    // AI Advisor & Skill Gap Predictor
    'ai.title': 'एआय कौशल्य व करिअर सल्लागार',
    'ai.subtitle': 'वैयक्तिक कौशल्य अंतर विश्लेषण, अभ्यासक्रम शिफारसी आणि सानुकूल रोडमॅप',
    'ai.tab_predictor': 'कौशल्य अंतर अंदाज व रोडमॅप',
    'ai.tab_chat': 'एआय करिअर संवाद',
    'ai.step1_title': '१. इच्छित करिअर पद निवडा',
    'ai.step2_title': '२. तुमची सद्य कौशल्ये',
    'ai.edu_level': 'शिक्षण पातळी',
    'ai.pace': 'साप्ताहिक वेळ',
    'ai.readiness_title': 'करिअर तयारी मूल्यांकन',
    'ai.acquired_skills': 'उपलब्ध कौशल्ये',
    'ai.skill_gaps': 'आवश्यक कौशल्य अंतर (Gaps)',
    'ai.rec_course': 'शिफारस केलेला अभ्यासक्रम',
    'ai.rec_lab': 'प्रात्यक्षिक लॅब',
    'ai.roadmap_title': 'टप्प्याटप्प्याने वैयक्तिकृत शिक्षण व लॅब रोडमॅप',

    // Lecture & Learn
    'lecture.lang_select': 'व्याख्यान भाषा',
    'lecture.download_pdf': 'लेक्चर नोट्स डाउनलोड करा (PDF)',
    'lecture.download_guide': 'प्रात्यक्षिक मार्गदर्शिका डाउनलोड करा (PDF)',
    'lecture.download_cheatsheet': 'महत्त्वाचे सूत्रे व चीटशीट डाउनलोड करा',
    'lecture.complete_next': 'पूर्ण करा आणि पुढील धडा',
    'lecture.take_quiz': 'सर्व धडे पूर्ण करा आणि क्विझ द्या',
    'lecture.quiz_title': 'अभ्यासक्रम कौशल्य चाचणी क्विझ',
    'lecture.submit_quiz': 'क्विझ सबमिट करा आणि कौशल्य तपासा',
    'lecture.cert_earned': 'अधिकृत प्रमाणपत्र प्राप्त झाले',
    'lecture.curriculum': 'अभ्यासक्रमातील धडे',
    'lecture.technical_overview': 'तांत्रिक माहिती व प्रात्यक्षिक महत्त्व',
    'lecture.equipment_setup': 'आवश्यक उपकरणे व लॅब मांडणी',
    'lecture.safety_tips': 'सुरक्षा नियम व महत्त्वाच्या सूचना',

    // Progress & Profile
    'progress.title': 'विद्यार्थी प्रगती व प्रोफाइल',
    'progress.subtitle': 'तुमच्या अभ्यासक्रमांची प्रगती, बुक केलेल्या लॅब्स आणि करिअर तयारीचा मागोवा घ्या.',
    'progress.enrolled_courses': 'माझे प्रवेश घेतलेले अभ्यासक्रम',
    'progress.lab_bookings': 'माझे लॅब बुकिंग',
    'progress.profile_details': 'प्रोफाइल माहिती व प्राधान्ये',
    'progress.education': 'शिक्षण',
    'progress.skills': 'कौशल्ये',
    'progress.interests': 'आवड व क्षेत्र',
    'progress.career_goal': 'करिअर ध्येय',
    'progress.trainer_panel': 'प्रशिक्षक: विद्यार्थी नोंदणी व प्रगती',
    'progress.recruiter_panel': 'कंपनी: उमेदवार अर्ज व शॉर्टलिस्टिंग',
    'progress.admin_panel': 'अॅडमिन कन्सोल: प्रणाली विहंगावलोकन व भूमिका नियंत्रण',

    // Auth & Form
    'auth.login_title': 'RuralLearn मध्ये पुन्हा स्वागत आहे',
    'auth.register_title': 'नवीन RuralLearn खाते तयार करा',
    'auth.email': 'ईमेल पत्ता',
    'auth.password': 'पासवर्ड',
    'auth.name': 'पूर्ण नाव',
    'auth.role': 'भूमिका निवडा',
    'auth.no_account': 'खाते नाही का?',
    'auth.have_account': 'आधीच खाते आहे का?',
    'footer.text': '© २०२४ RuralLearn. ग्रामीण तरुणांचे तांत्रिक सक्षमीकरण.'
  },
  hi: {
    // Navigation
    'nav.home': 'मुख्य पृष्ठ',
    'nav.courses': 'पाठ्यक्रम',
    'nav.labs': 'प्रयोगशालाएँ',
    'nav.certifications': 'प्रमाणपत्र',
    'nav.internships': 'अवसर एवं नौकरियां',
    'nav.ai_advisor': 'एआई सलाहकार',
    'nav.progress': 'मेरी प्रगति',
    'nav.login': 'लॉग इन',
    'nav.register': 'पंजीकरण',
    'nav.logout': 'लॉग आउट',
    'nav.notifications': 'सूचनाएं',

    // Hero & Home
    'hero.title': 'ग्रामीण शिक्षा का सशक्तिकरण',
    'hero.subtitle': 'विश्वस्तरीय तकनीकी शिक्षण संसाधन प्राप्त करें, लैब बुक करें और ग्रामीण युवाओं के लिए इंटर्नशिप खोजें।',
    'hero.cta': 'शुरू करें',
    'hero.welcome_back': 'पुनः स्वागत है',
    'hero.dashboard_sub': 'अपनी तकनीकी यात्रा जारी रखने के लिए नीचे दिए गए पोर्टल पर जाएं।',
    'stats.students': 'नामांकित विद्यार्थी',
    'stats.labs': 'सहयोगी प्रयोगशालाएँ',
    'stats.courses': 'उपलब्ध पाठ्यक्रम',
    'stats.internships': 'इंटर्नशिप व नौकरियां',

    // Sidebar Menus
    'menu.Dashboard': 'डैशबोर्ड',
    'menu.Courses': 'पाठ्यक्रम',
    'menu.Labs': 'प्रयोगशालाएँ',
    'menu.My Learning': 'मेरा शिक्षण',
    'menu.Progress': 'प्रगति',
    'menu.Quizzes': 'क्विज व परीक्षण',
    'menu.Certificates': 'प्रमाणपत्र',
    'menu.Opportunities/Apply': 'अवसर एवं आवेदन',
    'menu.AI Advisor': 'एआई सलाहकार',
    'menu.Notifications': 'सूचनाएं',
    'menu.Profile': 'प्रोफाइल',
    'menu.My Courses': 'मेरे पाठ्यक्रम',
    'menu.Create/Edit Courses': 'पाठ्यक्रम बनाएं/संपादित करें',
    'menu.Modules/Lectures': 'मॉड्यूल एवं व्याख्यान',
    'menu.Upload Videos/PDFs/Notes': 'संसाधन अपलोड करें',
    'menu.Enrollments': 'विद्यार्थी नामांकन',
    'menu.Student Progress': 'विद्यार्थी प्रगति',
    'menu.Create/Manage Jobs & Internships': 'नौकरी पोस्टिंग प्रबंधित करें',
    'menu.Applicants': 'उम्मीदवार आवेदक',
    'menu.Student Profiles': 'विद्यार्थी कौशल प्रोफाइल',
    'menu.Shortlist/Reject': 'शॉर्टलिस्ट एवं भर्ती',
    'menu.Application Status': 'आवेदन की स्थिति',
    'menu.Company Profile': 'कंपनी प्रोफाइल',
    'menu.Manage Students': 'विद्यार्थी प्रबंधन',
    'menu.Trainers': 'प्रशिक्षक प्रबंधन',
    'menu.Recruiters': 'नियोक्ता प्रबंधन',
    'menu.Opportunities': 'अवसर प्रबंधन',
    'menu.Users/Roles': 'उपयोगकर्ता एवं भूमिकाएं',
    'menu.Reports & Settings': 'रिपोर्ट एवं सेटिंग्स',
    'menu.portal': 'पोर्टल',

    // Buttons & Actions
    'btn.enroll_now': 'अभी नामांकन करें',
    'btn.continue_learning': 'सीखना जारी रखें',
    'btn.view_syllabus': 'पाठ्यक्रम देखें',
    'btn.start_course': 'पाठ्यक्रम शुरू करें',
    'btn.book_slot': 'लैब स्लॉट बुक करें',
    'btn.apply_now': 'आवेदन करें',
    'btn.submit_app': 'आवेदन जमा करें',
    'btn.cancel': 'रद्द करें',
    'btn.close': 'बंद करें',
    'btn.save': 'परिवर्तन सहेजें',
    'btn.edit': 'प्रोफाइल संपादित करें',
    'btn.view_cert': 'प्रमाणपत्र देखें',
    'btn.print_cert': 'डिप्लोमा प्रिंट / डाउनलोड करें',
    'btn.predict_gap': 'कौशल अंतर एवं रोडमैप देखें',
    'btn.regenerate': 'रोडमैप पुनः बनाएं',
    'btn.save_roadmap': 'प्रगति सहेजें',
    'btn.download_roadmap': 'रोडमैप डाउनलोड करें',
    'btn.copy': 'कॉपी करें',
    'btn.shortlist': 'शॉर्टलिस्ट',
    'btn.review': 'समीक्षा करें',
    'btn.reject': 'अस्वीकार करें',
    'btn.explore': 'देखें',

    // Categories & Filters
    'cat.all': 'सभी',
    'cat.hardware': 'हार्डवेयर',
    'cat.software': 'सॉफ्टवेयर',
    'cat.technology': 'प्रौद्योगिकी',
    'cat.agriculture': 'कृषि',
    'cat.business': 'व्यवसाय',
    'cat.categories': 'श्रेणियाँ',
    'cat.level': 'स्तर',
    'cat.beginner': 'शुरुआती (Beginner)',
    'cat.intermediate': 'मध्यवर्ती (Intermediate)',
    'cat.advanced': 'उन्नत (Advanced)',
    'cat.search_courses': 'शीर्षक, कौशल, हार्डवेयर या सॉफ्टवेयर से खोजें...',
    'cat.search_labs': 'लैब का नाम, स्थान या उपकरण से खोजें...',
    'cat.search_opps': 'नौकरियां, कंपनियां, कौशल या स्थान खोजें...',

    // Courses Page
    'courses.title': 'औद्योगिक और तकनीकी पाठ्यक्रम',
    'courses.subtitle': 'व्यावहारिक, स्थानीय और नौकरी के लिए तैयार तकनीकी पाठ्यक्रम प्रयोगशाला असाइनमेंट के साथ।',
    'courses.syllabus_title': 'पाठ्यक्रम विवरण एवं विषय',
    'courses.skills_gained': 'सीखे जाने वाले कौशल',
    'courses.modules_included': 'शामिल मॉड्यूल',
    'courses.duration': 'अवधि',
    'courses.provider': 'संस्थान / प्रदाता',

    // Labs Page
    'labs.title': 'प्रयोगशाला और कार्यशाला बुक करें',
    'labs.subtitle': 'कोपरगांव क्षेत्र में आधुनिक हार्डवेयर कार्यक्षेत्र, परीक्षण केंद्र और कंप्यूटर लैब का उपयोग करें।',
    'labs.available_slots': 'उपलब्ध स्लॉट',
    'labs.capacity': 'कुल क्षमता',
    'labs.facilities': 'प्रमुख सुविधाएं',
    'labs.equipment': 'उपकरण और वर्कस्टेशन',
    'labs.incharge': 'लैब प्रभारी / प्रशिक्षक',
    'labs.timings': 'समय',
    'labs.rules': 'सुरक्षा नियम एवं दिशानिर्देश',
    'labs.booking_title': 'लैब वर्कस्टेशन बुक करें',
    'labs.select_date': 'दिनांक चुनें',
    'labs.select_time': 'समय स्लॉट चुनें',
    'labs.purpose': 'व्यावहारिक उद्देश्य / प्रयोजन',
    'labs.confirm_booking': 'स्लॉट आरक्षित करें',
    'labs.booked_success': 'लैब सत्र सफलतापूर्वक बुक हो गया!',

    // Certifications Page
    'cert.title': 'आधिकारिक सत्यापित प्रमाणपत्र',
    'cert.subtitle': 'सत्यापित डिजिटल डिप्लोमा के साथ नियोक्ताओं और उद्योग जगत को अपनी तकनीकी दक्षता दिखाएं।',
    'cert.verified_badge': 'प्रमाणित एवं सत्यापित डिप्लोमा',
    'cert.issued_to': 'यह प्रमाणपत्र गर्व से प्रदान किया जाता है',
    'cert.for_mastering': 'इस विषय में व्यावहारिक दक्षता सफलतापूर्वक सिद्ध करने के लिए:',
    'cert.cert_id': 'प्रमाणपत्र संख्या',
    'cert.issued_date': 'जारी दिनांक',
    'cert.grade': 'दक्षता श्रेणी',
    'cert.authorized_by': 'अधिकृत परीक्षक',
    'cert.skills_verified': 'सत्यापित तकनीकी कौशल',
    'cert.no_certs': 'अभी कोई प्रमाणपत्र नहीं है। प्रमाणपत्र पाने के लिए पाठ्यक्रम पूरा करें और मूल्यांकन परीक्षा दें।',

    // Internships & Opportunities
    'internships.title': 'अवसर एवं प्लेसमेंट पोर्टल',
    'internships.subtitle': 'क्षेत्रीय नियोक्ताओं, कृषि तकनीक उद्यमों और औद्योगिक कार्यशालाओं से सीधे जुड़ें।',
    'internships.stipend': 'वेतन / मानदेय',
    'internships.location': 'स्थान',
    'internships.type': 'कार्य का प्रकार',
    'internships.deadline': 'अंतिम तिथि',
    'internships.eligibility': 'पात्रता',
    'internships.applied_badge': 'आवेदन किया गया',

    // AI Advisor & Skill Gap Predictor
    'ai.title': 'एआई करियर एवं कौशल सलाहकार',
    'ai.subtitle': 'व्यक्तिगत कौशल अंतर विश्लेषण, पाठ्यक्रम अनुशंसा और अनुकूलित रोडमैप',
    'ai.tab_predictor': 'कौशल अंतर अनुमान एवं रोडमैप',
    'ai.tab_chat': 'एआई करियर संवाद',
    'ai.step1_title': '1. लक्षित करियर पद चुनें',
    'ai.step2_title': '2. आपके वर्तमान कौशल',
    'ai.edu_level': 'शिक्षा स्तर',
    'ai.pace': 'साप्ताहिक समय',
    'ai.readiness_title': 'करियर तैयारी मूल्यांकन',
    'ai.acquired_skills': 'अर्जित कौशल',
    'ai.skill_gaps': 'पहचाने गए कौशल अंतर (Gaps)',
    'ai.rec_course': 'अनुशंसित पाठ्यक्रम',
    'ai.rec_lab': 'व्यावहारिक लैब',
    'ai.roadmap_title': 'चरणबद्ध व्यक्तिगत शिक्षण एवं लैब रोडमैप',

    // Lecture & Learn
    'lecture.lang_select': 'व्याख्यान भाषा',
    'lecture.download_pdf': 'व्याख्यान नोट्स डाउनलोड करें (PDF)',
    'lecture.download_guide': 'प्रायोगिक लैब गाइड डाउनलोड करें (PDF)',
    'lecture.download_cheatsheet': 'क्विक चीटशीट डाउनलोड करें',
    'lecture.complete_next': 'पूर्ण करें और अगला पाठ',
    'lecture.take_quiz': 'पाठ समाप्त करें और क्विज दें',
    'lecture.quiz_title': 'पाठ्यक्रम योग्यता मूल्यांकन क्विज',
    'lecture.submit_quiz': 'क्विज सबमिट करें और कौशल सत्यापित करें',
    'lecture.cert_earned': 'आधिकारिक प्रमाणपत्र अर्जित किया',
    'lecture.curriculum': 'पाठ्यक्रम के मॉड्यूल',
    'lecture.technical_overview': 'तकनीकी विवरण एवं व्यावहारिक उपयोग',
    'lecture.equipment_setup': 'अनुशंसित उपकरण एवं लैब सेटअप',
    'lecture.safety_tips': 'सुरक्षा दिशानिर्देश एवं फील्ड टिप्स',

    // Progress & Profile
    'progress.title': 'विद्यार्थी प्रगति एवं प्रोफाइल',
    'progress.subtitle': 'अपने पाठ्यक्रमों, लैब बुकिंग और करियर तत्परता को ट्रैक करें।',
    'progress.enrolled_courses': 'मेरे नामांकित पाठ्यक्रम',
    'progress.lab_bookings': 'मेरी लैब बुकिंग',
    'progress.profile_details': 'प्रोफाइल विवरण एवं प्राथमिकताएं',
    'progress.education': 'शिक्षा',
    'progress.skills': 'कौशल',
    'progress.interests': 'रुचि एवं क्षेत्र',
    'progress.career_goal': 'करियर लक्ष्य',
    'progress.trainer_panel': 'प्रशिक्षक: विद्यार्थी नामांकन एवं प्रगति',
    'progress.recruiter_panel': 'नियोक्ता: उम्मीदवार आवेदन एवं चयन',
    'progress.admin_panel': 'व्यवस्थापक: प्रणाली अवलोकन एवं भूमिका नियंत्रण',

    // Auth & Form
    'auth.login_title': 'RuralLearn में पुनः स्वागत है',
    'auth.register_title': 'नया RuralLearn खाता बनाएं',
    'auth.email': 'ईमेल पता',
    'auth.password': 'पासवर्ड',
    'auth.name': 'पूरा नाम',
    'auth.role': 'भूमिका चुनें',
    'auth.no_account': 'खाता नहीं है?',
    'auth.have_account': 'पहले से खाता है?',
    'footer.text': '© 2024 RuralLearn. ग्रामीण युवाओं का तकनीकी सशक्तिकरण।'
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('rurallearn_language');
    if (saved === 'mr' || saved === 'hi' || saved === 'en') return saved;
    return 'en';
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('rurallearn_language', lang);
  };

  const t = (key: string) => {
    return translations[language]?.[key] || translations['en']?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

